import type { AIModelsData } from '../types/aiModels'

export const aiModelsData: AIModelsData = {
  models: [
    {
      id: 1,
      name: 'Red Light Detector',
      type: 'red-light',
      typeLabel: 'Red Light',
      version: 'v1.2.0',
      confidence: 97,
      status: 'active',
      lastUpdated: '2026-09-28',
      description: 'Detects vehicles crossing during a red traffic signal.',
    },
    {
      id: 2,
      name: 'Stop Line Detector',
      type: 'stop-line',
      typeLabel: 'Stop Line',
      version: 'v1.1.0',
      confidence: 94,
      status: 'active',
      lastUpdated: '2026-09-24',
      description: 'Detects vehicles crossing designated stop lines.',
    },
    {
      id: 3,
      name: 'Helmet Detection Model',
      type: 'helmet',
      typeLabel: 'No Helmet',
      version: 'v2.0.1',
      confidence: 98,
      status: 'active',
      lastUpdated: '2026-09-30',
      description: 'Detects motorcycle riders who are not wearing helmets.',
    },
    {
      id: 4,
      name: 'Vehicle Speed Detector',
      type: 'speed',
      typeLabel: 'Speeding',
      version: 'v1.3.2',
      confidence: 91,
      status: 'active',
      lastUpdated: '2026-09-21',
      description: 'Identifies vehicles exceeding configured speed limits.',
    },
    {
      id: 5,
      name: 'Red Light Detector Legacy',
      type: 'red-light',
      typeLabel: 'Red Light',
      version: 'v1.0.0',
      confidence: 89,
      status: 'inactive',
      lastUpdated: '2026-07-15',
      description: 'Previous version of the red light detection model.',
    },
    {
      id: 6,
      name: 'Helmet Detection Legacy',
      type: 'helmet',
      typeLabel: 'No Helmet',
      version: 'v1.4.0',
      confidence: 92,
      status: 'inactive',
      lastUpdated: '2026-06-28',
      description: 'Previous helmet detection model kept for reference.',
    },
  ],
}