import type { UsersData } from '../types/users'

export const usersData: UsersData = {
  users: [
    {
      id: 1,
      name: 'Admin User',
      email: 'admin@trafficai.com',
      role: 'administrator',
      status: 'active',
      lastActive: 'Just now',
      joinedDate: '2026-01-15',
    },
    {
      id: 2,
      name: 'Bikash Sharma',
      email: 'bikash@trafficai.com',
      role: 'officer',
      status: 'active',
      lastActive: '5 min ago',
      joinedDate: '2026-02-10',
    },
    {
      id: 3,
      name: 'Sita Thapa',
      email: 'sita@trafficai.com',
      role: 'officer',
      status: 'active',
      lastActive: '18 min ago',
      joinedDate: '2026-02-21',
    },
    {
      id: 4,
      name: 'Ramesh Adhikari',
      email: 'ramesh@trafficai.com',
      role: 'officer',
      status: 'inactive',
      lastActive: '2 days ago',
      joinedDate: '2026-03-05',
    },
    {
      id: 5,
      name: 'Anisha Karki',
      email: 'anisha@trafficai.com',
      role: 'officer',
      status: 'active',
      lastActive: '32 min ago',
      joinedDate: '2026-03-18',
    },
    {
      id: 6,
      name: 'Prakash Gurung',
      email: 'prakash@trafficai.com',
      role: 'administrator',
      status: 'active',
      lastActive: '1 hour ago',
      joinedDate: '2026-04-02',
    },
    {
      id: 7,
      name: 'Nabin Shrestha',
      email: 'nabin@trafficai.com',
      role: 'officer',
      status: 'inactive',
      lastActive: '5 days ago',
      joinedDate: '2026-04-17',
    },
    {
      id: 8,
      name: 'Saroj KC',
      email: 'saroj@trafficai.com',
      role: 'officer',
      status: 'active',
      lastActive: '2 hours ago',
      joinedDate: '2026-05-01',
    },
  ],
}