import type { VehiclesData } from '../types/vehicles'

export const vehiclesData: VehiclesData = {
  vehicles: [
    {
      id: 1,
      plateNumber: 'BA 2 PA 4821',
      type: 'bike',
      make: 'Honda',
      model: 'CB Shine',
      color: 'Black',
      ownerName: 'Bikash Sharma',
      status: 'active',
      lastDetected: '2 min ago',
      registeredDate: '2026-01-18',
    },
    {
      id: 2,
      plateNumber: 'BA 3 CHA 7210',
      type: 'car',
      make: 'Hyundai',
      model: 'i20',
      color: 'White',
      ownerName: 'Sita Thapa',
      status: 'active',
      lastDetected: '8 min ago',
      registeredDate: '2026-02-04',
    },
    {
      id: 3,
      plateNumber: 'BA 1 JA 9034',
      type: 'car',
      make: 'Toyota',
      model: 'Corolla',
      color: 'Silver',
      ownerName: 'Ramesh Adhikari',
      status: 'active',
      lastDetected: '15 min ago',
      registeredDate: '2026-02-12',
    },
    {
      id: 4,
      plateNumber: 'BA 5 KHA 1832',
      type: 'bike',
      make: 'Yamaha',
      model: 'FZ',
      color: 'Blue',
      ownerName: 'Anisha Karki',
      status: 'inactive',
      lastDetected: '2 days ago',
      registeredDate: '2026-02-25',
    },
    {
      id: 5,
      plateNumber: 'BA 4 CHA 5521',
      type: 'bus',
      make: 'Tata',
      model: 'Starbus',
      color: 'Red',
      ownerName: 'Kathmandu Transport',
      status: 'active',
      lastDetected: '32 min ago',
      registeredDate: '2026-03-08',
    },
    {
      id: 6,
      plateNumber: 'BA 6 PA 3147',
      type: 'car',
      make: 'Kia',
      model: 'Seltos',
      color: 'Grey',
      ownerName: 'Prakash Gurung',
      status: 'active',
      lastDetected: '1 hour ago',
      registeredDate: '2026-03-19',
    },
    {
      id: 7,
      plateNumber: 'BA 7 KHA 6184',
      type: 'truck',
      make: 'Ashok Leyland',
      model: 'Ecomet',
      color: 'White',
      ownerName: 'Nabin Shrestha',
      status: 'inactive',
      lastDetected: '5 days ago',
      registeredDate: '2026-04-02',
    },
    {
      id: 8,
      plateNumber: 'BA 8 PA 4729',
      type: 'bike',
      make: 'Bajaj',
      model: 'Pulsar 150',
      color: 'Red',
      ownerName: 'Saroj KC',
      status: 'active',
      lastDetected: '2 hours ago',
      registeredDate: '2026-04-15',
    },
  ],
}