import type { ViolationsData } from '../types/violations'

export const violationsData: ViolationsData = {
  violations: [
    {
      id: 1,
      vehicleNumber: 'BA 2 PA 4821',
      violationType: 'red-light',
      violationLabel: 'Red Light Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 97,
      date: '2026-10-01',
      time: '19:52:14',
      status: 'pending',
    },
    {
      id: 2,
      vehicleNumber: 'BA 3 CHA 7210',
      violationType: 'helmet',
      violationLabel: 'No Helmet',
      camera: 'Camera 02',
      location: 'Putalisadak',
      confidence: 98,
      date: '2026-10-01',
      time: '19:48:32',
      status: 'rejected',
    },
    {
      id: 3,
      vehicleNumber: 'BA 1 JA 9034',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 94,
      date: '2026-10-01',
      time: '19:45:08',
      status: 'pending',
    },
    {
      id: 4,
      vehicleNumber: 'BA 5 KHA 1832',
      violationType: 'speed',
      violationLabel: 'Speeding',
      camera: 'Camera 02',
      location: 'Putalisadak',
      confidence: 96,
      date: '2026-10-01',
      time: '19:41:27',
      status: 'rejected',
    },
    {
      id: 5,
      vehicleNumber: 'BA 4 CHA 5521',
      violationType: 'red-light',
      violationLabel: 'Red Light Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 95,
      date: '2026-10-01',
      time: '19:35:42',
      status: 'pending',
    },
    {
      id: 6,
      vehicleNumber: 'BA 7 PA 2145',
      violationType: 'helmet',
      violationLabel: 'No Helmet',
      camera: 'Camera 03',
      location: 'Koteshwor Junction',
      confidence: 92,
      date: '2026-10-01',
      time: '19:31:16',
      status: 'rejected',
    },
    {
      id: 7,
      vehicleNumber: 'BA 2 KHA 6734',
      violationType: 'speed',
      violationLabel: 'Speeding',
      camera: 'Camera 02',
      location: 'Putalisadak',
      confidence: 91,
      date: '2026-10-01',
      time: '19:26:51',
      status: 'pending',
    },
    {
      id: 8,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'confirmed',
    },
    {
      id: 9,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'confirmed',
    },
    {
      id: 10,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'confirmed',
    },
    {
      id: 11,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'rejected',
    },
    {
      id: 12,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'rejected',
    },
    {
      id: 13,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'confirmed',
    },
    {
      id: 14,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'rejected',
    },
    {
      id: 15,
      vehicleNumber: 'BA 6 CHA 9087',
      violationType: 'stop-line',
      violationLabel: 'Stop Line Violation',
      camera: 'Camera 01',
      location: 'New Road Junction',
      confidence: 93,
      date: '2026-10-01',
      time: '19:21:39',
      status: 'rejected',
    },
  ],
}